# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(370, 214)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_bg = QtWidgets.QLabel(self.centralwidget)
        self.title_bg.setGeometry(QtCore.QRect(60, 10, 256, 64))
        self.title_bg.setObjectName("title_bg")
        self.title_text = QtWidgets.QLabel(self.centralwidget)
        self.title_text.setGeometry(QtCore.QRect(60, 10, 256, 64))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_text.sizePolicy().hasHeightForWidth())
        self.title_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Minecraft AE")
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.title_text.setFont(font)
        self.title_text.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.title_text.setTextFormat(QtCore.Qt.AutoText)
        self.title_text.setAlignment(QtCore.Qt.AlignCenter)
        self.title_text.setObjectName("title_text")
        self.lever_1 = QtWidgets.QLabel(self.centralwidget)
        self.lever_1.setGeometry(QtCore.QRect(150, 155, 72, 24))
        self.lever_1.setObjectName("lever_1")
        self.lever_2 = QtWidgets.QLabel(self.centralwidget)
        self.lever_2.setGeometry(QtCore.QRect(105, 85, 160, 160))
        self.lever_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lever_2.setObjectName("lever_2")
        self.desktop = QtWidgets.QLabel(self.centralwidget)
        self.desktop.setGeometry(QtCore.QRect(0, 175, 370, 40))
        self.desktop.setAlignment(QtCore.Qt.AlignCenter)
        self.desktop.setObjectName("desktop")
        self.lever_2.raise_()
        self.title_bg.raise_()
        self.title_text.raise_()
        self.lever_1.raise_()
        self.desktop.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "锐捷云课堂？/kill"))
        self.title_bg.setText(_translate("MainWindow", "我是背景"))
        self.title_text.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">/kill RCManager.exe</span></p></body></html>"))
        self.lever_1.setText(_translate("MainWindow", "我是拉杆底座"))
        self.lever_2.setText(_translate("MainWindow", "我是拉杆"))
        self.desktop.setText(_translate("MainWindow", "我是台子"))
